### ISSUE TITLE
Another issue with java.util.NoSuchElementException

### ISSUE THREAD

**Issue by audimann** [confluentinc/kafka-rest#116]
Hi Folks,
We have a cluster of 3 zookeppers and a cluster of 3 kafka servers freshly installed with teh latest confluent bits. We now get an error checking for the partition information of a topic

[pmehrig@obdmgt00 ~]$ curl http://bktv0000:8082/topics/
["_schemas","gduranceau-test","pmehrig_test"][pmehrig@obdmgt00 ~]$
[pmehrig@obdmgt00 ~]$ curl http://bktv0000:8082/topics/pmehrig_test
{"name":"pmehrig_test","configs":{},"partitions":[{"partition":2,"leader":0,"replicas":[{"broker":0,"leader":true,"in_sync":true},{"broker":2,"leader":false,"in_sync":true},{"broker":1,"leader":false,"in_sync":true}]},{"partition":1,"leader":2,"replicas":[{"broker":2,"leader":true,"in_sync":true},{"broker":1,"leader":false,"in_sync":true},{"broker":0,"leader":false,"in_sync":true}]},{"partition":0,"leader":1,"replicas":[{"broker":1,"leader":true,"in_sync":true},{"broker":0,"leader":false,"in_sync":true},{"broker":2,"leader":false,"in_sync":true}]}]}[pmehrig@obdmgt00 ~]$
[pmehrig@obdmgt00 ~]$ curl http://bktv0000:8082/topics/pmehrig_test/partitions
{"error_code":500,"message":"Internal Server Error"}[pmehrig@obdmgt00 ~]$

The stacktrace on the kafka server is close but not identical to the previous issue with the NoSuchElementException:
java.util.NoSuchElementException: None.get
        at scala.None$.get(Option.scala:313)
        at scala.None$.get(Option.scala:311)
        at io.confluent.kafkarest.MetadataObserver.extractPartitionsFromZKData(MetadataObserver.java:154)
        at io.confluent.kafkarest.MetadataObserver.getTopicsData(MetadataObserver.java:105)
        at io.confluent.kafkarest.MetadataObserver.getTopics(MetadataObserver.java:74)
        at io.confluent.kafkarest.MetadataObserver.topicExists(MetadataObserver.java:81)
        at io.confluent.kafkarest.resources.PartitionsResource.topicExists(PartitionsResource.java:159)
        at io.confluent.kafkarest.resources.PartitionsResource.checkTopicExists(PartitionsResource.java:163)
        at io.confluent.kafkarest.resources.PartitionsResource.list(PartitionsResource.java:62)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:195)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:406)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:350)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:106)
        at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:259)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
        at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:319)
        at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:236)
        at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1028)
        at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
        at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:219)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:229)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
        at org.eclipse.jetty.server.Server.handle(Server.java:370)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
        at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
        at java.lang.Thread.run(Thread.java:745)

Any idea what might be wrong? This is RHEL 6.7
[root@bktv0000 ~]# rpm -qa | grep confl
confluent-rest-utils-1.0.1-2.noarch
confluent-kafka-2.11.5-0.8.2.2-2.noarch
confluent-common-1.0.1-2.noarch
confluent-kafka-rest-1.0.1-2.noarch
confluent-schema-registry-1.0.1-2.noarch

Many thanks in advance

    Michael

**Comment by inadler** [comment]
It happened to me when I tried to delete a topic

**Comment by ewencp** [comment]
This has been fixed by #144
