### ISSUE TITLE
Setting fetch.max.message.bytes doesn't work

### ISSUE THREAD

**Issue by Nesze** [confluentinc/kafka-rest#120]
Version: v1.0.1

My config file looks like:
```
id=kafka-rest-proxy
port=8080
zookeeper.connect=zk1:2181,zk2:2181,zk3:2181
fetch.max.message.bytes=16777216
consumer.request.max.bytes=17825792
```

With these settings, the proxy still logs MessageTooLargeException whenever a larger message (tested with > 2MB) is being fetched. 

```
ERROR [2015-10-29 15:14:47,110] io.confluent.kafkarest.ConsumerReadTask: Unexpected exception in consumer read thread:  [Thread-2hread]
kafka.common.MessageSizeTooLargeException: Found a message larger than the maximum fetch size of this consumer on topic PublicationEvents partition 6 at fetch offset 2134. Increase the fetch size, or decrease the maximum message size the broker will allow.
        at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:90)
        at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
        at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
        at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
        at io.confluent.kafkarest.ConsumerReadTask.doPartialRead(ConsumerReadTask.java:116)
        at io.confluent.kafkarest.ConsumerWorker.run(ConsumerWorker.java:90)
```

At start-up the `fetch.max.message.bytes` is missing from the config logs (https://pastee.org/dzenj)  and shortly after the following is logged: https://pastee.org/bn9m3 (which is also strange).

We have also looked into the code, but couldn't find where this property is set.

Let me know if I can help you with anything.

**Comment by Nesze** [comment]
Doh, it's `fetch.message.max.bytes` not `fetch.max.message.bytes`.
