### ISSUE TITLE
ERROR Producer error for request io.confluent.kafkarest.ProduceTask@675e803

### ISSUE THREAD

**Issue by Shumkov** [confluentinc/kafka-rest#140]
My kafka setup:
2 virtual hosts. `confluent-kafka-2.10.5 0.9.0.0-1` and `confluent-kafka-rest 2.0.0-1`          

```
id=kafka-rest-1
# kafka-rest-2 on second
zookeeper.connect=kafka1-sandbox3v.dev.itim.vn:2181,kafka2-sandbox3v.dev.itim.vn:2181/kafka
```

After upgrade kafka from 0.8 to 0.9 kafka (and rest proxy too) i see strange error in kafka rest log:
```
[2015-12-14 18:34:38,569] ERROR Producer error for request io.confluent.kafkarest.ProduceTask@2b41cdbc (io.confluent.kafkarest.ProduceTask:71)
org.apache.kafka.common.errors.NetworkException: The server disconnected before a response was received.
[2015-12-14 18:34:38,572] ERROR Uncaught error in kafka producer I/O thread:  (org.apache.kafka.clients.producer.internals.Sender:130)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'throttle_time_ms': java.nio.BufferUnderflowException
	at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:71)
	at org.apache.kafka.clients.NetworkClient.handleCompletedReceives(NetworkClient.java:464)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:279)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:216)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:128)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Shumkov** [comment]
After downgrade kafka to 0.8 and kafka-rest to 1.0 everything works well.

**Comment by ewencp** [comment]
Right, this is one kind of error you'll get if you use a newer client with an older broker.
