### ISSUE TITLE
Deployment instructions are incorrect

### ISSUE THREAD

**Issue by aragnon** [confluentinc/kafka-rest#176]
Your instructions state that one only needs to run `bin/kafka-rest-start`, which I did from the `/usr` directory on Ubuntu 14.04 LTS. This however results in an "unexpected error" as can be seen below. Hence, I would like to see that you correct this. By the time that you fix this, I will probably have already worked around it, but I'd rather just have working software to begin with, thanks. I am using the latest binaries distributed by your organisation. 

```
[2016-04-06 12:11:35,952] INFO Opening socket connection to server localhost/127.0.0.1:2181 (org.apache.zookeeper.ClientCnxn:933)
[2016-04-06 12:11:35,953] INFO Client will not SASL-authenticate because the default JAAS configuration section 'Client' could not be found. If you are not using SASL, you may ignore this. On the other hand, if you expected SASL to work, please fix your JAA
S configuration. (org.apache.zookeeper.client.ZooKeeperSaslClient:125)
[2016-04-06 12:11:35,953] WARN Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn:1057)
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
        at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:286)
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1035)
```

**Comment by ewencp** [comment]
@aragnon This looks like you don't have zookeeper running. As described in the [installation instructions|http://docs.confluent.io/2.0.1/kafka-rest/docs/intro.html#installation], the default config works if you have Zookeeper and Kafka running locally on the default ports (i.e. with their default configurations). If Zookeeper is not running on `localhost:2181` or Kafka is not available on `localhost:9092`, then you'll want to create a config to override these settings (see, e.g., `/etc/kafka-rest/kafka-rest.properties`).
