### ISSUE TITLE
Can't get maven lib

### ISSUE THREAD

**Issue by skyqty** [confluentinc/kafka-rest#191]
Hi,I can' get lib from your repository url(http://packages.confluent.io/maven/)
and error log:
`2016-04-29 10:34:35,808 [69874809]   WARN -      #org.jetbrains.idea.maven - Failed to update Maven indices for: [confluent] http://packages.confluent.io/maven 
org.jetbrains.idea.maven.server.MavenServerIndexerException: java.lang.RuntimeException: java.io.FileNotFoundException: Resource nexus-maven-repository-index.properties does not exist
	at org.jetbrains.idea.maven.server.Maven3ServerIndexerImpl.updateIndex(Maven3ServerIndexerImpl.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$256(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)`

**Comment by ewencp** [comment]
@skyqty This is an [IntelliJ bug](https://youtrack.jetbrains.com/issue/IDEA-138029) -- it assumes non-standard features of the maven repository.

[This stackoverflow question](http://stackoverflow.com/questions/34104305/resource-nexus-maven-repository-index-properties-does-not-exist-in-intellij) suggests a possible solution.

**Comment by skyqty** [comment]
@ewencp 
Thank you for your reply,
In this [stackoverflow question](http://stackoverflow.com/questions/34104305/resource-nexus-maven-repository-index-properties-does-not-exist-in-intellij),I dont't know how to add grails to intelliJ project,so I try Eclipse import maven project,but some dependency missing ,like:
_Missing artifact org.apache.kafka:kafka_2.11:jar:test:0.10.0.0-SNAPSHOT
Missing artifact io.confluent:rest-utils:jar:3.0.0-SNAPSHOT_

**Comment by skyqty** [comment]
OK,this issue can be close.....
I change pom to
`<confluent.version>2.0.1</confluent.version>
 <kafka.version>0.9.0.1-cp1</kafka.version>`
the problem solved.

**Comment by ewencp** [comment]
@skyqty Yeah, we don't publish snapshot builds to our public maven repository. Generally when developing against `master` branches you'll need to grab any dependencies from their `master` branch as well. Glad you figured it out!

**Comment by skyqty** [comment]
o(^▽^)o
