### ISSUE TITLE
MessageSizeTooLargeException when consuming the topic

### ISSUE THREAD

**Issue by goblinhecker** [confluentinc/kafka-rest#254]
Hello,

Earlier, I was having trouble inserting a large object to Confluent, but after reading the comments in Issue #208 (https://github.com/confluentinc/kafka-rest/issues/208), I was able to bypass the error. 

However, I'm having trouble consuming the topic. I'm using kafka-avro-console-consumer script, with max.partition.fetch.bytes set to 15728640 in consumer.properties. The large object I've inserted is 2.1 Mb in size, so if baffles me that I cannot consume the topic.

My Confluent Version is 3.0.0, and Kafka Version is 0.10.0. 
I have restarted the Kafka services but cannot find resolution.

The full error: 
[2016-11-22 10:14:28,418] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$:103)
kafka.common.MessageSizeTooLargeException: Found a message larger than the maximum fetch size of this consumer on topic <topic> partition 0 at fetch offset 0. Increase the fetch size, or decrease the maximum message size the broker will allow.
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:90)
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
	at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
	at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
	at kafka.consumer.OldConsumer.receive(BaseConsumer.scala:102)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:117)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:73)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:51)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
[2016-11-22 10:14:28,418] ERROR Error processing message, terminating consumer process:  (kafka.tools.ConsoleConsumer$:103)
kafka.common.MessageSizeTooLargeException: Found a message larger than the maximum fetch size of this consumer on topic <topic> partition 0 at fetch offset 0. Increase the fetch size, or decrease the maximum message size the broker will allow.
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:90)
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
	at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:64)
	at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:56)
	at kafka.consumer.OldConsumer.receive(BaseConsumer.scala:102)
	at kafka.tools.ConsoleConsumer$.process(ConsoleConsumer.scala:117)
	at kafka.tools.ConsoleConsumer$.run(ConsoleConsumer.scala:73)
	at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:51)
	at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
Processed a total of 0 messages

**Comment by ewencp** [comment]
@goblinhecker The REST proxy is still using the old consumer and the console consumer in 0.10.0 still defaults to the old consumer as well (this changed to the new consumer in the recent 0.10.1 release). `max.partition.fetch.bytes` is for the new consumer, so the setting you need is old `fetch.message.max.bytes`.

**Comment by goblinhecker** [comment]
I made the above changes and it worked. Thank you.

Note: provide "--consumer.config etc/kafka/consumer.properties" parameter while consuming the topic to let consumer know which properties to use.

**Comment by gaur19** [comment]
Hi i tried finding solution to this problem but almost every problem is for older version of kafka which has different config files as compared to one i m using which means those solutions r not working . Btw i m using Kafka_2.11-1.1.0 version, So can u guys help me..?                                                        gaur@ubuntu:~/kafka_2.11-1.1.0$ bin/kafka-console-producer.sh --broker-list localhost:9092 --topic Zomato-O < ~/imply-2.6.0/quickstart/Zomato-O.json
>[2018-07-12 15:44:19,416] ERROR Error when sending message to topic Zomato-O with key: null, value: 5747970 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.RecordTooLargeException: The message is 5748058 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.
