### ISSUE TITLE
empty message in kafka leads to exception

### ISSUE THREAD

**Issue by alexanikanov** [confluentinc/kafka-rest#269]
steps:

- run console consumer
- push empty message (press "return")
- consume topic (eg, using kafka-ui)

result:
```
[2017-02-16 21:06:20,148] INFO 172.16.37.8 - - [16/Feb/2017:21:06:20 +0000] "GET /consumers/Consumer-1487279179560-json/instances/instance/topics/session?max_bytes=50000 HTTP/1.1" 500 183  72 (io.confluent
.rest-utils.requests)
[2017-02-16 21:06:20,148] ERROR Unexpected exception in consumer read thread:  (io.confluent.kafkarest.ConsumerReadTask)
org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: [B@5d12df9d; line: 1, column: 1]
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: [B@5d12df9d; line: 1, column: 1]
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3609)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3549)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2673)
        at io.confluent.kafkarest.JsonConsumerState.deserialize(JsonConsumerState.java:76)
        at io.confluent.kafkarest.JsonConsumerState.createConsumerRecord(JsonConsumerState.java:66)
        at io.confluent.kafkarest.ConsumerReadTask.doPartialRead(ConsumerReadTask.java:119)
        at io.confluent.kafkarest.ConsumerWorker.run(ConsumerWorker.java:90)
```

**Comment by danielavtodorova** [comment]
is there any solution yet for this? Running into the same issue..
