### ISSUE TITLE
 No security protocol defined for listener PLAINTEXTSASL

### ISSUE THREAD

**Issue by QingyangKong** [confluentinc/kafka-rest#278]
Hello, I am trying to use KafkaRestProxy (3.2.0) in company's kerberized HDP cluster(zk 3.4.6, kafka 2.10 ). When I started by command `./bin/kafka-rest-start ./etc/kafka-rest/kafka-rest.properties` I ran into following issue. It seems that I need to set security protocol for PLAINTEXTSASL, but where to set it?
After some research in source code, SASL_PLAINTEXT is the security protocol name. What if zookeeper only sends broker info as "PLAINTEXTSASL://xxxx" rather than "SASL_PLAINTEXT://xxxxx"?

```
[2017-03-13 13:43:40,151] ERROR Server died unexpectedly:  (io.confluent.kafkarest.KafkaRestMain:59)
kafka.common.KafkaException: Failed to parse the broker info from zookeeper: {"jmx_port":-1,"timestamp":"1489003262165","endpoints":["PLAINTEXTSASL://xxxxxx.com:6667"],"host":null,"version":3,"port":-1}
        at kafka.cluster.Broker$.createBroker(Broker.scala:125)
        at kafka.utils.ZkUtils.getBrokerInfo(ZkUtils.scala:799)
        at kafka.utils.ZkUtils$$anonfun$getAllBrokersInCluster$2.apply(ZkUtils.scala:253)
        at kafka.utils.ZkUtils$$anonfun$getAllBrokersInCluster$2.apply(ZkUtils.scala:253)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at kafka.utils.ZkUtils.getAllBrokersInCluster(ZkUtils.scala:253)
        at io.confluent.kafkarest.ProducerPool.getBootstrapBrokers(ProducerPool.java:142)
        at io.confluent.kafkarest.ProducerPool.<init>(ProducerPool.java:59)
        at io.confluent.kafkarest.ProducerPool.<init>(ProducerPool.java:54)
        at io.confluent.kafkarest.KafkaRestApplication.setupInjectedResources(KafkaRestApplication.java:83)
        at io.confluent.kafkarest.KafkaRestApplication.setupResources(KafkaRestApplication.java:58)
        at io.confluent.kafkarest.KafkaRestApplication.setupResources(KafkaRestApplication.java:39)
        at io.confluent.rest.Application.createServer(Application.java:149)
        at io.confluent.rest.Application.start(Application.java:416)
        at io.confluent.kafkarest.KafkaRestMain.main(KafkaRestMain.java:52)
Caused by: java.lang.IllegalArgumentException: No security protocol defined for listener PLAINTEXTSASL
        at kafka.cluster.EndPoint$$anonfun$securityProtocol$1$1.apply(EndPoint.scala:48)
        at kafka.cluster.EndPoint$$anonfun$securityProtocol$1$1.apply(EndPoint.scala:48)
        at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
        at scala.collection.AbstractMap.getOrElse(Map.scala:59)
        at kafka.cluster.EndPoint$.securityProtocol$1(EndPoint.scala:47)
        at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:56)
        at kafka.cluster.Broker$$anonfun$2.apply(Broker.scala:115)
        at kafka.cluster.Broker$$anonfun$2.apply(Broker.scala:115)
        at scala.collection.immutable.List.map(List.scala:273)
        at kafka.cluster.Broker$.createBroker(Broker.scala:115)
        ... 19 more
```

**Comment by mageshn** [comment]
@QingyangKong how does the listener config look on the broker side? PLAINTEXTSASL isn't a valid protocol at all. Irrespective, you can also use the bootstrap.servers instead of the zookeeper.connect and give the broker URL directly.
