### ISSUE TITLE
NPE when `ssl.key.password` is empty

### ISSUE THREAD

**Issue by cotedm** [confluentinc/kafka-rest#282]
When enabling HTTPS, if you leave `ssl.key.password` empty, you can get the NullPointerException below. It looks to be a Jetty thing, but maybe we can do better here with some configuration validation warning and fail more gracefully than exposing an NPE. Anyone who knows more Jetty, if this is a known issue on that side might make sense to upgrade the dependency to grab the fix?

[2017-03-24 01:57:08,079] WARN FAILED SslContextFactory@bc4d5e1(/etc/kafka-rest/secrets/kafka.producer.keystore.jks,/etc/kafka-rest/secrets/kafka.producer.truststore.jks): java.lang.NullPointerException (org.eclipse.jetty.util.component.AbstractLifeCycle)
java.lang.NullPointerException
	at org.eclipse.jetty.util.ssl.SslContextFactory.getKeyManagers(SslContextFactory.java:911)
	at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:300)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:64)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:256)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.confluent.rest.Application.start(Application.java:418)
	at io.confluent.kafkarest.KafkaRestMain.main(KafkaRestMain.java:52)

**Comment by ewencp** [comment]
@cotedm Presumably this is because we are getting the `ssl.key.password` from the config, which is `null`, and then passing it to Jetty. It probably isn't Jetty's fault, we probably just need to validate the value from the config before passing it to Jetty.

But `ssl.key.password` and `clients.ssl.key.password` seem to have `""` as default values, so I'm unclear where the `null` is coming from exactly.
