### ISSUE TITLE
NullPointerException when GET /records after I configured SASL Authentication between REST Proxy and Apache Kafka Brokers

### ISSUE THREAD

**Issue by CoolYJCK** [confluentinc/kafka-rest#386]
Hello, everybody, 
     I got a java.lang.NullPointerException when "GET /consumers/my_json_consumer/instances/my_consumer_instance/records" after I configured SASL Authentication between REST Proxy and Apache Kafka Brokers. 

The configuration options in kafka-rest.properties:

id=kafka-rest-test-server-01
schema.registry.url=http://99.12.120.10:8081
zookeeper.connect=99.12.120.4:2181
bootstrap.servers=SASL_PLAINTEXT://99.12.120.1:9093,SASL_PLAINTEXT://99.12.120.2:9093,SASL_PLAINTEXT://99.12.120.3:9093
listeners=http://99.12.120.10:8082

# Security Configuration Options
client.security.protocol=SASL_PLAINTEXT
client.sasl.mechanism=PLAIN
client.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
  username="lily" \
  password="lily123";

The detailed exception info is as below:

[2018-01-23 14:15:15,308] INFO ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = earliest
	bootstrap.servers = [SASL_PLAINTEXT://99.12.120.1:9093, SASL_PLAINTEXT://99.12.120.2:9093, SASL_PLAINTEXT://99.12.120.3:9093]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = my_json_consumer
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	internal.leave.group.on.close = true
	isolation.level = read_uncommitted
	key.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 1000
	retry.backoff.ms = 100
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = PLAIN
	security.protocol = SASL_PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.ByteArrayDeserializer
 (org.apache.kafka.clients.consumer.ConsumerConfig:223 in AbstractConfig.java)
[2018-01-23 14:15:15,350] INFO 99.12.120.178 - - [23/Jan/2018:14:15:15 +0800] "POST /consumers/my_json_consumer HTTP/1.0" 200 127  94 (io.confluent.rest-utils.requests:77 in Slf4jRequestLog.java)
[2018-01-23 14:15:23,205] INFO 99.12.120.178 - - [23/Jan/2018:14:15:23 +0800] "POST /consumers/my_json_consumer/instances/my_consumer_instance/subscription HTTP/1.0" 204 0  27 (io.confluent.rest-utils.requests:77 in Slf4jRequestLog.java)
[2018-01-23 14:15:28,426] INFO 99.12.120.178 - - [23/Jan/2018:14:15:28 +0800] "GET /consumers/my_json_consumer/instances/my_consumer_instance/records HTTP/1.0" 500 50  8 (io.confluent.rest-utils.requests:77 in Slf4jRequestLog.java)
[2018-01-23 14:15:28,428] ERROR Unexpected exception in consumer read task id=io.confluent.kafkarest.v2.KafkaConsumerReadTask@2023f9fe  (io.confluent.kafkarest.v2.KafkaConsumerReadTask:154 in KafkaConsumerReadTask.java)
java.lang.NullPointerException
	at io.confluent.kafkarest.v2.KafkaConsumerState.getOrCreateConsumerRecords(KafkaConsumerState.java:407)
	at io.confluent.kafkarest.v2.KafkaConsumerState.hasNext(KafkaConsumerState.java:426)
	at io.confluent.kafkarest.v2.KafkaConsumerReadTask.doPartialRead(KafkaConsumerReadTask.java:104)
	at io.confluent.kafkarest.v2.KafkaConsumerWorker.run(KafkaConsumerWorker.java:112)

I don't know this is why.  Because when I "POST /topics/test" after I configured SASL Authentication between REST Proxy and Apache Kafka Brokers, it's OK.  So producing messages is ok, but consuming messages throws NullPointerException. Why is it? Is it a bug?

**Comment by CoolYJCK** [comment]
additional remarks: I use kafka-rest 4.0.0 and kafka 1.0.0.

**Comment by adnankobir** [comment]
I'm also experiencing the same issue, I've read elsewhere that this can happen if the instance ID's are the same, in my case i've left it to the default, which autogenerates Instance IDs. In my case i'm not using SASL authentication and this occurs any time i use multiple consumers.

**Comment by ambhojgoyal** [comment]
@adnankobir  @CoolYJCK Did you guys found the solution for this.
I am also facing the same issue

**Comment by adnankobir** [comment]
@ambhojgoyal for me setting consumer threads did the trick - in my case setting it via env var KAFKA_REST_CONSUMER_THREADS since we run in k8s.

**Comment by sbelyankin** [comment]
@adnankobir please elaborate on your solution. What did you set the number of consumer threads to?
