### ISSUE TITLE
Zookeeper is not reconnected when connection is lost and DNS changes

### ISSUE THREAD

**Issue by Vanuan** [confluentinc/kafka-rest#444]
When you connect to zookeeper:2181 there's no guarantee that ip would be static. But kafka rest assumes ip never changes, so this exception is thrown when it happens:

```
[2018-07-06 01:07:49,323] INFO Opening socket connection to server 10.0.3.25/10.0.3.25:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2018-07-06 01:07:50,775] WARN Session 0x16453b31d55000a for server null, unexpected error, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)

```

It looks like doesn't try to resolve DNS name when reconnecting.

**Comment by Vanuan** [comment]
So kafka rest should either quit if NoRouteToHostException is encountered or reinitialize ZkUtils. Alternatively, this should be fixed in ZkUtils itself
