### ISSUE TITLE
2 Schema Registy Instances Failing to Start

### ISSUE THREAD

**Issue by buntyray** [confluentinc/kafka-rest#446]
We have 3 Schema Registry In cluster.
Version of confluent : 3.3.0

[2018-07-11 00:17:24,203] INFO Initialized last consumed offset to -1 (io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread:143)
[2018-07-11 00:17:24,205] INFO [kafka-store-reader-thread-_schemas]: Starting (io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread:70)
[2018-07-11 00:17:24,433] ERROR KafkaStoreReader thread has died for an unknown reason. (io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread:214)
[2018-07-11 00:17:24,434] ERROR [kafka-store-reader-thread-_schemas]: Error due to (io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread:105)
java.lang.RuntimeException: java.lang.NullPointerException
        at io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread.doWork(KafkaStoreReaderThread.java:215)
        at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:64)
Caused by: java.lang.NullPointerException
        at io.confluent.kafka.schemaregistry.storage.KafkaStoreMessageHandler.handleDeleteSubject(KafkaStoreMessageHandler.java:62)
        at io.confluent.kafka.schemaregistry.storage.KafkaStoreMessageHandler.handleUpdate(KafkaStoreMessageHandler.java:49)
        at io.confluent.kafka.schemaregistry.storage.KafkaStoreMessageHandler.handleUpdate(KafkaStoreMessageHandler.java:24)
        at io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread.doWork(KafkaStoreReaderThread.java:192)
        ... 1 more
[2018-07-11 00:17:24,436] INFO [kafka-store-reader-thread-_schemas]: Stopped (io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread:70)
[2018-07-11 00:17:24,463] INFO Wait to catch up until the offset of the last message at 75 (io.confluent.kafka.schemaregistry.storage.KafkaStore:405)
[2018-07-11 00:18:24,464] ERROR Error starting the schema registry (io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication:58)
io.confluent.kafka.schemaregistry.exceptions.SchemaRegistryInitializationException: Error initializing kafka store while initializing schema registry
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:214)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:56)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryRestApplication.setupResources(SchemaRegistryRestApplication.java:38)
        at io.confluent.rest.Application.createServer(Application.java:157)
        at io.confluent.kafka.schemaregistry.rest.SchemaRegistryMain.main(SchemaRegistryMain.java:44)
Caused by: io.confluent.kafka.schemaregistry.storage.exceptions.StoreInitializationException: io.confluent.kafka.schemaregistry.storage.exceptions.StoreTimeoutException: KafkaStoreReaderThread failed to reach target offset within the timeout interval. targetOffset: 75, offsetReached: 40, timeout(ms): 60000
        at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:181)
        at io.confluent.kafka.schemaregistry.storage.KafkaSchemaRegistry.init(KafkaSchemaRegistry.java:212)
        ... 4 more
Caused by: io.confluent.kafka.schemaregistry.storage.exceptions.StoreTimeoutException: KafkaStoreReaderThread failed to reach target offset within the timeout interval. targetOffset: 75, offsetReached: 40, timeout(ms): 60000
        at io.confluent.kafka.schemaregistry.storage.KafkaStoreReaderThread.waitUntilOffset(KafkaStoreReaderThread.java:258)
        at io.confluent.kafka.schemaregistry.storage.KafkaStore.waitUntilKafkaReaderReachesLastOffset(KafkaStore.java:406)
        at io.confluent.kafka.schemaregistry.storage.KafkaStore.init(KafkaStore.java:179)

-----------------------------------  Configuration --------------

listeners=https://0.0.0.0:8443
host.name=<hostname>
port=8443
kafkastore.connection.url=<zk_host1>:2181,<zk_host2>:2181<zk_host3>:2181,<zk_host4>:2181,<zk_hos5>:2181/kafka
kafkastore.bootstrap.servers=SSL://<hostname1>.com:9093,SSL://<hostname2>:9093,SSL://<hostname3>:9093,SSL://<hostname4>:9093,SSL://<hostname5>:9093
kafkastore.security.protocol=SSL
master.eligibility=true
kafkastore.topic=_schemas
kafkastore.zk.session.timeout.ms=240000
kafkastore.topic.replication.factor=3
debug=false
access.control.allow.methods=GET,POST,PUT,OPTIONS
access.control.allow.origin=*
#schema.registry.zk.namespace=kafkaschema
#security.protocol=SSL
kafkastore.ssl.keystore.location=/opt/wagapp/ssl/<CertIdentity>.jks
kafkastore.ssl.keystore.password=xxxxx
kafkastore.ssl.truststore.location=/opt/wagapp/ssl/<TrustStrore>.jks
kafkastore.ssl.truststore.password=changeme1
ssl.keystore.location=/opt/wagapp/ssl/<CertIdentity>.jks
ssl.keystore.password=xxxx
ssl.key.password=xxxx
ssl.truststore.location=/opt/wagapp/ssl/<TrustStrore>.jks
ssl.truststore.password=changeme1

**Comment by cmeury** [comment]
This is the `kafka-rest` repository, though.
