### ISSUE TITLE
Zstd compression unknown 

### ISSUE THREAD

**Issue by zthulj** [confluentinc/kafka-rest#532]
When trying to consume data compressed with zStandard (producer with kafka-clients 2.1.0). I've got this error : 

```
ERROR Unexpected exception in consumer read task id=io.confluent.kafkarest.v2.KafkaConsumerReadTask@3634e2ec  (io.confluent.kafkarest.v2.KafkaConsumerReadTask)
java.lang.IllegalArgumentException: Unknown compression type id: 4
	at org.apache.kafka.common.record.CompressionType.forId(CompressionType.java:160)
	at org.apache.kafka.common.record.DefaultRecordBatch.compressionType(DefaultRecordBatch.java:212)
	at org.apache.kafka.common.record.AbstractRecordBatch.isCompressed(AbstractRecordBatch.java:33)
	at org.apache.kafka.common.record.DefaultRecordBatch.isCompressed(DefaultRecordBatch.java:96)
	at org.apache.kafka.common.record.DefaultRecordBatch.streamingIterator(DefaultRecordBatch.java:334)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.nextFetchedRecord(Fetcher.java:1102)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.fetchRecords(Fetcher.java:1139)
	at org.apache.kafka.clients.consumer.internals.Fetcher$PartitionRecords.access$1400(Fetcher.java:993)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchRecords(Fetcher.java:527)
	at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:488)
	at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1185)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1115)
	at io.confluent.kafkarest.v2.KafkaConsumerState.getOrCreateConsumerRecords(KafkaConsumerState.java:395)
	at io.confluent.kafkarest.v2.KafkaConsumerState.hasNext(KafkaConsumerState.java:371)
	at io.confluent.kafkarest.v2.KafkaConsumerReadTask.addRecords(KafkaConsumerReadTask.java:141)
	at io.confluent.kafkarest.v2.KafkaConsumerReadTask.doPartialRead(KafkaConsumerReadTask.java:99)
	at io.confluent.kafkarest.v2.KafkaConsumerManager$RunnableReadTask.run(KafkaConsumerManager.java:370)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

I've seen Kafka-rest works on kafka-clients 1.1

Can we switch to the latest version ?

**Comment by allamiro** [comment]
version compatibility issue i assume you might need to check your kafka client version and your kafka version.

**Comment by zthulj** [comment]
If a producer doesn't use Kafka-rest but a client, he's able to publish messages compressed with zstd.
Kafka-Rest is using kafka-clients 1.1.0. This is the reason of this error.

This issue to open the discussion about upgrading to the latest version, so as to be able to handle zstd compression.
