### ISSUE TITLE
Issues with fetching records

### ISSUE THREAD

**Issue by dalu** [confluentinc/kafka-rest#633]
Following the docs I have sent those 2 curl requests

```
$ curl -X POST -H "Content-Type: application/vnd.kafka.v2+json" --data '{"topics":["posts"]}' \
 http://localhost:8082/consumers/my_json_consumer/instances/my_consumer_instance/subscription
# No content in response

$ curl -X GET -H "Accept: application/vnd.kafka.json.v2+json" \
      http://localhost:8082/consumers/my_json_consumer/instances/my_consumer_instance/records
```

The latter returns

```
curl -v -X GET -H "Accept: application/vnd.kafka.json.v2+json" \
      http://localhost:8082/consumers/my_json_consumer/instances/my_consumer_instance/records
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying ::1:8082...
* Connected to localhost (::1) port 8082 (#0)
> GET /consumers/my_json_consumer/instances/my_consumer_instance/records HTTP/1.1
> Host: localhost:8082
> User-Agent: curl/7.69.0
> Accept: application/vnd.kafka.json.v2+json
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 10 Mar 2020 20:07:22 GMT
< Content-Type: application/vnd.kafka.json.v2+json
< Content-Length: 237
< 
* Connection #0 to host localhost left intact
{"error_code":50002,"message":"com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'd5f8eacd': was expecting ('true', 'false' or 'null')\n at [Source: (byte[])\"d5f8eacd-01dc-4192-acba-7adccbc12234\"; line: 1, column: 10]"}%
```

```
[2020-03-10 21:01:28,017] INFO Kafka version: 5.4.0-ce (org.apache.kafka.common.utils.AppInfoParser)
[2020-03-10 21:01:28,018] INFO Kafka commitId: 10767fc4b1a20c9b (org.apache.kafka.common.utils.AppInfoParser)
[2020-03-10 21:01:28,018] INFO Kafka startTimeMs: 1583870488017 (org.apache.kafka.common.utils.AppInfoParser)
[2020-03-10 21:01:28,019] INFO interceptor=confluent.monitoring.interceptor.consumer-my_json_consumer-1 created for client_id=consumer-my_json_consumer-1 client_type=CONSUMER session= cluster=LIcYidSRR6OQyD1BQMCoMA group=my_json_consumer (io.confluent.monitoring.clients.interceptor.MonitoringInterceptor)
[2020-03-10 21:01:28,022] ERROR Kafka exception (io.confluent.rest.exceptions.KafkaExceptionMapper)
org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'd5f8eacd': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"d5f8eacd-01dc-4192-acba-7adccbc12234"; line: 1, column: 10]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'd5f8eacd': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"d5f8eacd-01dc-4192-acba-7adccbc12234"; line: 1, column: 10]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3532)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2627)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:832)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4142)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3092)
        at io.confluent.kafkarest.v2.JsonKafkaConsumerState.deserialize(JsonKafkaConsumerState.java:66)
        at io.confluent.kafkarest.v2.JsonKafkaConsumerState.createConsumerRecord(JsonKafkaConsumerState.java:51)
        at io.confluent.kafkarest.v2.KafkaConsumerReadTask.maybeAddRecord(KafkaConsumerReadTask.java:157)
        at io.confluent.kafkarest.v2.KafkaConsumerReadTask.addRecords(KafkaConsumerReadTask.java:141)
        at io.confluent.kafkarest.v2.KafkaConsumerReadTask.doPartialRead(KafkaConsumerReadTask.java:98)
        at io.confluent.kafkarest.v2.KafkaConsumerManager$RunnableReadTask.run(KafkaConsumerManager.java:405)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[2020-03-10 21:01:28,024] INFO 0:0:0:0:0:0:0:1 - - [10/Mar/2020:20:01:27 +0000] "GET /consumers/my_json_consumer/instances/my_consumer_instance/records HTTP/1.1" 500 237  452 (io.confluent.rest-utils.requests)
[2020-03-10 21:01:28,024] ERROR Unexpected exception in consumer read task id=io.confluent.kafkarest.v2.KafkaConsumerReadTask@36c47e1d  (io.confluent.kafkarest.v2.KafkaConsumerReadTask)
org.apache.kafka.common.errors.SerializationException: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'd5f8eacd': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"d5f8eacd-01dc-4192-acba-7adccbc12234"; line: 1, column: 10]
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'd5f8eacd': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"d5f8eacd-01dc-4192-acba-7adccbc12234"; line: 1, column: 10]
        at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1804)
        at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:703)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._reportInvalidToken(UTF8StreamJsonParser.java:3532)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._handleUnexpectedValue(UTF8StreamJsonParser.java:2627)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._nextTokenNotInObject(UTF8StreamJsonParser.java:832)
        at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextToken(UTF8StreamJsonParser.java:729)
        at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4142)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4001)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3092)
        at io.confluent.kafkarest.v2.JsonKafkaConsumerState.deserialize(JsonKafkaConsumerState.java:66)
        at io.confluent.kafkarest.v2.JsonKafkaConsumerState.createConsumerRecord(JsonKafkaConsumerState.java:51)
        at io.confluent.kafkarest.v2.KafkaConsumerReadTask.maybeAddRecord(KafkaConsumerReadTask.java:157)
        at io.confluent.kafkarest.v2.KafkaConsumerReadTask.addRecords(KafkaConsumerReadTask.java:141)
        at io.confluent.kafkarest.v2.KafkaConsumerReadTask.doPartialRead(KafkaConsumerReadTask.java:98)
        at io.confluent.kafkarest.v2.KafkaConsumerManager$RunnableReadTask.run(KafkaConsumerManager.java:405)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
[2020-03-10 21:01:28,521] INFO [Producer clientId=confluent.monitoring.interceptor.consumer-my_json_consumer-1] Cluster ID: LIcYidSRR6OQyD1BQMCoMA (org.apache.kafka.clients.Metadata)
```

Those are the records that should've been returned

```
[{"order":1,"ROWTIME":1583862717738,"ROWKEY":"d5f8eacd-01dc-4192-acba-7adccbc12234","ID":"d5f8eacd-01dc-4192-acba-7adccbc12234","BODY":"BqJjpQyiPFAJ6YT4","DATE":"2020-03-10T18:51:57.738670654+01:00"},{"order":2,"ROWTIME":1583862772130,"ROWKEY":"adbaa565-c6fe-4fc4-8b6c-29f4d805646b","ID":"adbaa565-c6fe-4fc4-8b6c-29f4d805646b","BODY":"30M1nbRoEETgQ1Cm","DATE":"2020-03-10T18:52:52.129709689+01:00"},{"order":3,"ROWTIME":1583862773281,"ROWKEY":"160c024b-8af2-454d-875b-b2aed00f2915","ID":"160c024b-8af2-454d-875b-b2aed00f2915","BODY":"cSAqDZRFpqVy4q4E","DATE":"2020-03-10T18:52:53.281690926+01:00"},{"order":4,"ROWTIME":1583862773982,"ROWKEY":"49f0647d-50b9-4e85-bbfc-8f6c8bc0dc90","ID":"49f0647d-50b9-4e85-bbfc-8f6c8bc0dc90","BODY":"rY18Qs3fputuEkOa","DATE":"2020-03-10T18:52:53.981956762+01:00"},{"order":5,"ROWTIME":1583862774970,"ROWKEY":"cb6daef3-a0ef-45d5-867f-8644669fe43d","ID":"cb6daef3-a0ef-45d5-867f-8644669fe43d","BODY":"4yfmnEbJdSwVubBG","DATE":"2020-03-10T18:52:54.970182394+01:00"},{"order":6,"ROWTIME":1583862775600,"ROWKEY":"01900c63-ee34-4075-b060-6ec46b9c2ad2","ID":"01900c63-ee34-4075-b060-6ec46b9c2ad2","BODY":"mWOFFfbK7zqtZ8g3","DATE":"2020-03-10T18:52:55.600277757+01:00"},{"order":7,"ROWTIME":1583862776161,"ROWKEY":"3e678553-f9f8-4bce-823d-e5557fb9f659","ID":"3e678553-f9f8-4bce-823d-e5557fb9f659","BODY":"YMVlDikpIRRAMI5E","DATE":"2020-03-10T18:52:56.161118704+01:00"},{"order":8,"ROWTIME":1583862776731,"ROWKEY":"10e713a6-3b19-4ae7-873d-d1d317789afe","ID":"10e713a6-3b19-4ae7-873d-d1d317789afe","BODY":"jH0YzRoECAYJNoI6","DATE":"2020-03-10T18:52:56.731381199+01:00"},{"order":9,"ROWTIME":1583862936196,"ROWKEY":"8cc624fb-8fe3-4976-b82a-01c5e3184509","ID":"8cc624fb-8fe3-4976-b82a-01c5e3184509","BODY":"ZJQn7c6A9Ia0yvc5","DATE":"2020-03-10T18:55:36.195933054+01:00"}]
```

The messages were created using the Go client
```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"time"

	"github.com/confluentinc/confluent-kafka-go/kafka"
	"github.com/dchest/uniuri"
	"github.com/gofrs/uuid"
)

type Post struct {
	ID   uuid.UUID
	Body string
	Date time.Time
}

func main() {
	conf := &kafka.ConfigMap{"bootstrap.servers": "127.0.0.1:9092"}
	p, e := kafka.NewProducer(conf)
	if e != nil {
		log.Fatal(e.Error())
	}
	deliveryChan := make(chan kafka.Event)

	topic := "posts"

	post := new(Post)
	post.ID, _ = uuid.NewV4()
	// post.ID, _ = uuid.FromString("8cc624fb-8fe3-4976-b82a-01c5e3184509")
	post.Body = uniuri.New()
	post.Date = time.Now()

	postJson, _ := json.Marshal(post)

	msg := &kafka.Message{
		TopicPartition: kafka.TopicPartition{
			Topic:     &topic,
			Partition: kafka.PartitionAny,
		},
		Value: postJson,
		Key:   []byte(post.ID.String()),
	}

	e = p.Produce(msg, deliveryChan)
	evt := <-deliveryChan
	m := evt.(*kafka.Message)

	if m.TopicPartition.Error != nil {
		fmt.Printf("Delivery failed: %v\n", m.TopicPartition.Error)
	} else {
		fmt.Printf("Delivered message to topic %s [%d] at offset %v\n",
			*m.TopicPartition.Topic, m.TopicPartition.Partition, m.TopicPartition.Offset)
	}

	close(deliveryChan)
}
```

This request does nothing, it does not subscribe to the `posts` topic:

```
curl -X POST -H "Content-Type: application/vnd.kafka.v2+json" --data '{"topics":["posts"]}' \
 http://localhost:8082/consumers/my_json_consumer/instances/my_consumer_instance/subscription
```

In the control center I can see the `my_json_consumer` but topics count is 0.

**Comment by rigelbm** [comment]
REST Proxy production and consumption has the limitation that both key and value must use the same serialization format. Here you are trying to read a message as JSON. Because of that it will try to deserialize both the key and the value as JSON. Although the value is valid JSON, you are using a string UUID as the key. The REST Proxy is failing to deserialize that as JSON. This is the `Unrecognized token 'd5f8eacd': was expecting ('true', 'false' or 'null')
 at [Source: (byte[])"d5f8eacd-01dc-4192-acba-7adccbc12234"` the exception you pasted. The `d5f8eacd-01dc-4192-acba-7adccbc12234` piece is the key that the REST Proxy is trying to deserialize as JSON.

**Comment by dalu** [comment]
Thanks for feedback. I'm not sure how to remedy that.
Also `"some string here"` is valid JSON, but `{"some string here"}` is not.

Having a JSON string as key, e.g. `{"ID":"d5f8eacd-01dc-4192-acba-7adccbc12234"}` and I have never used an object/class/struct as key before seems odd.

The key is pretty much irrelevant for my SPA. I mean I would use the REST proxy for talking to Kafka, right? Do you usually have a JSON serialized key? If I could just query for the records. I'm supplying a key because I need one apparently to create a table and also doing that in the control center doesn't work, despite me telling it to use `Post.ID` (or rather just ID) as key in the create table form.

I have so many questions. This is day 2 with Kafka for me.
For instance can I "subscribe to a stream" using the REST proxy? If yes, does it use EventSource or a websocket for delivery? If not, would I have to write my own middleware(/proxy) or are there tools that do?
With subscribe to a stream I mean, while the client SPA is running, getting updates as they occur, via EventSource or WebSocket, not by regular query.

Also I noticed that, unlike in my Go consumer, the consumer that is created with the REST proxy disappears after a while and I have to send the whole chain of requests, creating a consumer, subscribing to a topic and finally fetching data all over again.
