### ISSUE TITLE
Avro RecordNameStrategy not working properly

### ISSUE THREAD

**Issue by wtrzcinski** [confluentinc/kafka-rest#666]
Hi, I try to send messages to the kafka through the kafka-rest proxy with custom avro schemas per record. I tried to setup proper SubjectNameStrategy using properties in /etc/kafka-rest/kafka-rest.properties configuration file:

```
KAFKA_REST_client.key.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
KAFKA_REST_client.value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
```

And I met very strange behavior as if the kafka-rest proxy tried to register my schemas twice. Once under "topic-name-key", "topic-name-value" subject names and once under actual record names. As visible in following logs from schema-registry container:

```
...
kafka-schemaregistry_1  | [2020-05-06 09:30:18,570] INFO Wait to catch up until the offset of the last message at 1 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,605] INFO 172.20.0.4 - - [06/May/2020:09:30:18 +0000] "POST /subjects/search.hit-key/versions HTTP/1.1" 200 8  261 (io.confluent.rest-utils.requests)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,609] INFO Wait to catch up until the offset of the last message at 2 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,619] INFO 172.20.0.4 - - [06/May/2020:09:30:18 +0000] "POST /subjects/search.hit-value/versions HTTP/1.1" 200 8  12 (io.confluent.rest-utils.requests)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,655] INFO Wait to catch up until the offset of the last message at 3 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,670] INFO 172.20.0.4 - - [06/May/2020:09:30:18 +0000] "POST /subjects/com.mycompany.search.monitoring.model.SearchKey/versions HTTP/1.1" 200 8  17 (io.confluent.rest-utils.requests)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,675] INFO Wait to catch up until the offset of the last message at 4 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,684] INFO 172.20.0.4 - - [06/May/2020:09:30:18 +0000] "POST /subjects/com.mycompany.search.monitoring.model.JobStart/versions HTTP/1.1" 200 8  11 (io.confluent.rest-utils.requests)
...
```

For the next records, which have different avro schema, the registry complains with following logs:
```
...
kafka-schemaregistry_1  | [2020-05-06 09:30:18,814] INFO 172.20.0.4 - - [06/May/2020:09:30:18 +0000] "POST /subjects/search.hit-value/versions HTTP/1.1" 409 93  19 (io.confluent.rest-utils.requests)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,845] INFO Wait to catch up until the offset of the last message at 5 (io.confluent.kafka.schemaregistry.storage.KafkaStore)
kafka-schemaregistry_1  | [2020-05-06 09:30:18,850] INFO 172.20.0.4 - - [06/May/2020:09:30:18 +0000] "POST /subjects/search.hit-value/versions HTTP/1.1" 409 93  9 (io.confluent.rest-utils.requests)
...
```
And the kafka rest proxy with the following exception:
```
kafka-rest_1            | [2020-05-06 09:30:18,825] INFO 172.20.0.1 - - [06/May/2020:09:30:18 +0000] "POST /topics/search.hit HTTP/1.1" 408 69  37 (io.confluent.rest-utils.requests)
kafka-rest_1            | [2020-05-06 09:30:18,850] ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper)
kafka-rest_1            | io.confluent.rest.exceptions.RestException: Schema registration or lookup failed
kafka-rest_1            | 	at io.confluent.kafkarest.SchemaRestProducer.produce(SchemaRestProducer.java:109)
kafka-rest_1            | 	at io.confluent.kafkarest.ProducerPool.produce(ProducerPool.java:209)
kafka-rest_1            | 	at io.confluent.kafkarest.resources.v2.TopicsResource.produce(TopicsResource.java:165)
kafka-rest_1            | 	at io.confluent.kafkarest.resources.v2.TopicsResource.produceSchema(TopicsResource.java:206)
kafka-rest_1            | 	at io.confluent.kafkarest.resources.v2.TopicsResource.produceAvro(TopicsResource.java:119)
kafka-rest_1            | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
kafka-rest_1            | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
kafka-rest_1            | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
kafka-rest_1            | 	at java.lang.reflect.Method.invoke(Method.java:498)
kafka-rest_1            | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
kafka-rest_1            | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
kafka-rest_1            | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
kafka-rest_1            | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:159)
kafka-rest_1            | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
kafka-rest_1            | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
kafka-rest_1            | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
kafka-rest_1            | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
kafka-rest_1            | 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
kafka-rest_1            | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
kafka-rest_1            | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
kafka-rest_1            | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
kafka-rest_1            | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
kafka-rest_1            | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
kafka-rest_1            | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
kafka-rest_1            | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
kafka-rest_1            | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
kafka-rest_1            | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
kafka-rest_1            | 	at org.glassfish.jersey.servlet.ServletContainer.serviceImpl(ServletContainer.java:386)
kafka-rest_1            | 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:561)
kafka-rest_1            | 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:502)
kafka-rest_1            | 	at org.glassfish.jersey.servlet.ServletContainer.doFilter(ServletContainer.java:439)
kafka-rest_1            | 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
kafka-rest_1            | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
kafka-rest_1            | 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1607)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
kafka-rest_1            | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
kafka-rest_1            | 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1577)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:146)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:221)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
kafka-rest_1            | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
kafka-rest_1            | 	at org.eclipse.jetty.server.Server.handle(Server.java:500)
kafka-rest_1            | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
kafka-rest_1            | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
kafka-rest_1            | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
kafka-rest_1            | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
kafka-rest_1            | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
kafka-rest_1            | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
kafka-rest_1            | 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
kafka-rest_1            | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
kafka-rest_1            | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
kafka-rest_1            | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
kafka-rest_1            | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
kafka-rest_1            | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
kafka-rest_1            | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
kafka-rest_1            | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
kafka-rest_1            | 	at java.lang.Thread.run(Thread.java:748)
kafka-rest_1            | Caused by: io.confluent.kafka.schemaregistry.client.rest.exceptions.RestClientException: Schema being registered is incompatible with an earlier schema; error code: 409
kafka-rest_1            | 	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:293)
kafka-rest_1            | 	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:352)
kafka-rest_1            | 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:495)
kafka-rest_1            | 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:486)
kafka-rest_1            | 	at io.confluent.kafka.schemaregistry.client.rest.RestService.registerSchema(RestService.java:459)
kafka-rest_1            | 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.registerAndGetId(CachedSchemaRegistryClient.java:206)
kafka-rest_1            | 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:268)
kafka-rest_1            | 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.register(CachedSchemaRegistryClient.java:244)
kafka-rest_1            | 	at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDe.register(AbstractKafkaSchemaSerDe.java:146)
kafka-rest_1            | 	at io.confluent.kafkarest.SchemaRestProducer.produce(SchemaRestProducer.java:102)
kafka-rest_1            | 	... 64 more
```

At a first glance the issue seems to be that your SchemaRestProducer doesn't understand the configured subject strategy but your KafkaAvroSerializer does.

Are you supporting this schema per record scenario and it is just a bug? Or you don't support this scenario and the "subject.name.strategy" configuration shouldn't be accepted by the KafkaAvroSerializer? (or KafkaAvroSerializer shouldn't auto register schema)

Best Regards
Wojtek

**Comment by benhag** [comment]
We have the same problem: key and value schema are registered twice when the `RecordNameStrategy`  is used. Once using the default `TopicNameStrategy` (e.g. `<topic-name>-key` and `<topic-name>-value`) and once using the configured `RecordNameStrategy`. 
The first message therefore defines the schema for the whole topic and it's not possible to sent messages using a different schema to the same topic.

Any news on this?

**Comment by noraab** [comment]
@wtrzcinski did you receive any response or found any solution?

**Comment by wtrzcinski** [comment]
Hi, sorry for late reply. No, I didn't get any response. It was long time ago, and I don't remember exactly, but as far as I remember the workaround was as follows:

At the very beginning we tried to send the message:

```
{
   'value_schema': ...,
   "records": [...]
}
```

And we expected that the endpoint would return id of the schema which we wanted to use later. But we met the issue I described above - generally this scenario seems to be not working for us. So, as workaround, on the client side for every schema we send directly a request to schema registry in order to create the schema and that request returns "schema_id" which we can use later in a kafka event request. And then we send the records with already existing schema ids:

```
{
    'key_schema_id': ...,
    'value_schema_id': ...,
    'records': [...]
}
```

Best Regards
Wojciech Trzciński

**Comment by benhag** [comment]
Requesting the schema ids from the schema-registry and sending them instead of the schema to the rest-proxy works.
Thanks for the workaround @wtrzcinski

**Comment by cobolbaby** [comment]
Any progress ?

**Comment by Fryie** [comment]
@cobolbaby To me, it looks like kafka-rest previously supported setting `key.subject.name.strategy` and `value.subject.name.strategy` at a global level which would appear to have worked in conjunction with setting the schema IDs explicitly. It looks like this configuration was removed in newer versions of kafka-rest (I don't know when exactly). I don't know if there is any other way of getting v2 to work. In v3, you can set the subject name strategy in the payload, which appears to work.

At least this is what I found out after attempting a pretty major update of kafka-rest.
