### ISSUE TITLE
500 Server Error while using seek offsets API

### ISSUE THREAD

**Issue by reddybhargava** [confluentinc/kafka-rest#951]
I'm trying to seek using this [API](https://docs.confluent.io/platform/current/kafka-rest/api.html#post--consumers-(string-group_name)-instances-(string-instance)-positions). But instead of using offsets, I'm using timestamps list as described in #769.

But when I try to seek to the beginning or end of the topic using timestamp and I'm getting `500 Internal Server Error`. 
Shouldn't this work ? 
Shouldn't it be equal to seeking to beginning and latest ? 
Or can we only seek to timestamps within the topic ? 

Here is a part of the error output - 
```
[2021-12-07 08:54:31,547] ERROR Unhandled exception (io.confluent.rest.exceptions.KafkaExceptionMapper:127)
java.lang.NullPointerException
        at io.confluent.kafkarest.v2.KafkaConsumerState.seek(KafkaConsumerState.java:210)
        at io.confluent.kafkarest.v2.KafkaConsumerManager.seek(KafkaConsumerManager.java:612)
        at io.confluent.kafkarest.resources.v2.ConsumersResource.seekToOffset(ConsumersResource.java:370)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
```

```
[2021-12-07 08:54:31,549] ERROR Unhandled exception resulting in internal server error response (io.confluent.rest.exceptions.GenericExceptionMapper:38)
java.lang.NullPointerException
        at io.confluent.kafkarest.v2.KafkaConsumerState.seek(KafkaConsumerState.java:210)
        at io.confluent.kafkarest.v2.KafkaConsumerManager.seek(KafkaConsumerManager.java:612)
        at io.confluent.kafkarest.resources.v2.ConsumersResource.seekToOffset(ConsumersResource.java:370)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
```

```
[2021-12-07 08:54:31,550] ERROR Request Failed with exception  (io.confluent.rest.exceptions.DebuggableExceptionMapper:103)
java.lang.NullPointerException
        at io.confluent.kafkarest.v2.KafkaConsumerState.seek(KafkaConsumerState.java:210)
        at io.confluent.kafkarest.v2.KafkaConsumerManager.seek(KafkaConsumerManager.java:612)
        at io.confluent.kafkarest.resources.v2.ConsumersResource.seekToOffset(ConsumersResource.java:370)
        at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
```

```
[2021-12-07 08:54:31,552] INFO 10.10.10.10 - - [07/Dec/2021:08:54:31 +0000] "POST /consumers/group_1/instances/ci_1/positions HTTP/1.1" 500 52  10 (io.confluent.rest-utils.requests:62)
```

Version - confluent-6.2.1

To Reproduce:
1. Create Consumer
2. Subscribe to topic
3. Get records (OPTIONAL: error happens with and without this step)
4. Seek using timestamps

**Comment by reddybhargava** [comment]
@rigelbm @mhowlett Could you guys please have a look at this ?

**Comment by ph1lm** [comment]
I noticed that it fails like that for empty partitions.
